#!/usr/bin/env python3
"""Generate `docs/sample_log.csv` - the committed, illustrative telemetry example.

    python tools/analytics/make_sample_log.py

The sample is the public face of the log format (referenced by docs/TELEMETRY_SCHEMA.md
and the analytics READMEs, and used as the parse/dashboard fixture). It is regenerated
from this script rather than hand-edited so it can never silently drift from the current
schema again (#166).

Hygiene: it uses a clearly-DEMO device identity and **no real MAC** - a public
sample must not carry a hardware address (the old hand-made sample leaked one).
It mirrors what `plants_logger_0_4` emits today (schema_version=1): raw + band are the
truth; the `pct` value is a labelled derived index, never presented as a measurement.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
_OUT = _REPO / "docs" / "sample_log.csv"

TZ = timezone(timedelta(hours=-5))  # tz_offset=-05:00 (matches the rig)
COLS = (
    "record_type,timestamp_utc,timestamp_local,sample_id,session_id,device_id,"
    "firmware_version,logger_version,millis_ms,sensor_model,sensor_id,sensor_position,"
    "channel,raw_value,value,unit,quality_flag,temp_context_c,rh_context_pct,"
    "pressure_context_hpa,event_id,payload,notes"
)

# sensor read order within a sweep, with its GPIO (from the boot banner's sensor map)
SWEEP = (("s3", 36), ("s4", 39), ("s1", 34), ("s2", 35))
OFFSETS = (0.0, 2.1, 2.2, 4.3)  # seconds between probes inside one burst

# Three rotation segments illustrating the band range: Moist -> Drying -> Parched.
SEGMENTS = (
    {"start": "2026-06-23T21:09:10Z", "session": "demo001", "level": "well watered",
     "base": 1305, "spread": (24, 31), "step": (7, 18, -6, 21)},
    {"start": "2026-06-24T00:00:11Z", "session": "demo002", "level": "needs water",
     "base": 1980, "spread": (22, 30), "step": (9, 24, -5, 16)},
    {"start": "2026-06-25T00:00:06Z", "session": "demo003", "level": "air-dry",
     "base": 3168, "spread": (26, 38), "step": (5, 11, -4, 14)},
)

# pct is a labelled *index* over the moist window [900, 3400], not a measurement.
_PCT_LO, _PCT_HI = 900, 3400


def _pct(raw: int) -> int:
    return max(0, min(100, round(100 * (_PCT_HI - raw) / (_PCT_HI - _PCT_LO))))


def _header(start: datetime, session: str) -> str:
    return "\n".join(
        (
            f"# log_start_utc={_iso(start)}  tz_offset=-05:00  "
            "logger=plants_logger_0_4  schema_version=1",
            "# boot plants controller fw=0.7.0 - Rung 4 schema v1, "
            "four soil sensors (read-only)",
            "# plants telemetry  schema_version=1  "
            "contract=docs/TELEMETRY_SCHEMA.md@v1",
            "# fw=0.7.0  git=demo0000  built=Jun 25 2026 18:39:19  "
            "run=4probe-coloc-origplant",
            "# device_id=plants_esp32_demo01  mac=<redacted>  chip=ESP32-D0WD-V3  "
            "adc=ADC1,12bit,11dB,eFuseCal=off",
            f"# session_id={session}  cadence_ms=30000",
            "# sensors: ch0=GPIO36/s3 ch1=GPIO39/s4 ch2=GPIO34/s1 ch3=GPIO35/s2  "
            "(model=UMLIFE_v2_TLC555 pos=origplant)",
            "# cal bounds(dry>wet): 3050 2140 1830 1520 1150 1050  [moist% 900..3400]",
            "# cfg: smp=100 trim=15 db=60 confirm_ms=3000/3000/2000 spr=250 discard=4",
            "# device_cols: record_type,session_id,device_id,fw,millis_ms,sensor_model,"
            "sensor_id,sensor_position,channel,raw_value,value,unit,quality_flag,payload",
            COLS,
            "",
        )
    )


def _iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.") + (
        f"{dt.microsecond // 1000:03d}Z"
    )


def _local(dt: datetime) -> str:
    loc = dt.astimezone(TZ)
    return loc.strftime("%Y-%m-%d %H:%M:%S.") + f"{loc.microsecond // 1000:03d}"


def main() -> None:
    out: list[str] = [
        "# SAMPLE telemetry log (illustrative; schema: docs/TELEMETRY_SCHEMA.md). "
        "Not real captured data.",
        "# Generated by tools/analytics/make_sample_log.py "
        "- DEMO identity, no real MAC.",
        "# The three header blocks below illustrate rotation segments - "
        "a new file/header opens per UTC",
        "# day or size cap. Parsers: skip lines starting with '#' and the "
        "column-name row; read data rows",
        "# whose first field is a record_type ('plants.soil').",
    ]
    sid = 0
    for seg in SEGMENTS:
        start = datetime.fromisoformat(seg["start"].replace("Z", "+00:00"))
        out.append(_header(start, seg["session"]))
        for sweep in range(2):  # two bursts per segment keeps it ~1 page
            burst = start + timedelta(seconds=30 * sweep)
            for (sensor, gpio), off, delta in zip(SWEEP, OFFSETS, seg["step"]):
                sid += 1
                ts = burst + timedelta(seconds=off)
                raw = seg["base"] + delta + sweep  # tiny drift between bursts
                spread = seg["spread"][sweep % 2]
                payload = f"level={seg['level']};role=diag;spread={spread};gpio={gpio}"
                row = [
                    "plants.soil", _iso(ts), _local(ts), str(sid), seg["session"],
                    "plants_esp32_demo01", "0.7.0", "plants_logger_0_4", "30000",
                    "UMLIFE_v2_TLC555", sensor, "origplant", "soil_moisture",
                    str(raw), str(_pct(raw)), "pct", "OK", "", "", "", "", payload, "",
                ]
                out.append(",".join(row))
        out.append("")  # blank line between segments

    # newline="\n": emit LF on every platform (repo policy; avoids a CRLF re-diff)
    _OUT.write_text("\n".join(out).rstrip("\n") + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {_OUT.relative_to(_REPO)} ({sid} data rows, 3 segments, no MAC)")


if __name__ == "__main__":
    main()
